services:
  - type: web
    name: inviteflow-web
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://inviteflow-3.onrender.com/api
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
